#!/usr/bin/env ruby
# Usage: coral filter-gh-project
# Summary: Extract owner & repo information from GitHub URLs
# Help: Scans STDIN for GitHub URLs, extracts the owner & repo information
# from them and outputs that information in "owner/repo-name" format.
#
# Supports the following URL formats:
#   - http://github.com/mislav/coral/...
#   - http://mislav.github.com/coral/...
#   - git://github.com/mislav/coral.git
#   - git@github.com:mislav/coral.git

name  = /\w[\w.-]*/
owner = /[a-zA-Z0-9-]+/
url1  = %r{ :// (?:wiki\.)?   github\.com / (#{owner}) / (#{name})  }x
url2  = %r{                 @ github\.com : (#{owner}) / (#{name})  }x
url3  = %r{ :// (#{owner}) \. github\.com / (#{name})               }x

while gets
  case $_
  when url1, url2
    puts "#$1/" + $2.sub(/\.git$/, '')
  when url3
    puts "#$1/#$2}"
  end
end
