#!/usr/bin/env bash
# Usage: coral commands [-v]
# Summary: List available commands
# Help: Lists coral commands available on the system.
# This searches the whole PATH for executables starting with "coral-".
#
# It outputs only the command names. To get full paths, use `-v`.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

[ "$1" = '-v' ] && verbose=true

shopt -s nullglob

{ for path in ${PATH//:/$'\n'}; do
    for command in "${path}/coral-"*; do
      if [ -x "$command" ]; then
        if [ -n $verbose ]; then
          echo $command
        else
          echo ${command##*coral-}
        fi
      fi
    done
  done
} | sort | uniq
