#!/usr/bin/env bash
# Usage: coral path <repo>[@<version>]
# Summary: Show filesystem path for a repo
# Help: Displays the full filesystem path for a repository in Coral.
#
# If there are multiple checkouts for a single repo, it displays the path for
# the main checkout by default (see `coral set-canonical`). You can target
# specific versions with <version>.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

name="$1"
repo_path="$CORAL_ROOT/repos/${name}"

shopt -s nullglob

if [[ $name = ${name%@*} ]]; then
  for repo_dir in "${repo_path}@"*; do
    if [[ ! -L ${repo_dir}/.git/config ]]; then
      echo "$repo_dir"
      exit 0
    fi
  done
elif [[ -d $repo_path ]]; then
  echo "$repo_path"
  exit 0
fi

echo "coral-path: could not find \`${name}'" >&2
exit 1
