#!/usr/bin/env ruby
# Usage: coral github-markup <file>
# Summary: Render HTML markup from a file
# Help: Renders markup from Markdown, Textile, RDoc, and other types of files
# the same way it is done on GitHub.com.

file = ARGV[0]

unless file and File.exist? file
  warn "usage: #$0 <file>"
  exit 2
end

old_level, $-w = $-w, nil

begin
  require 'github/markup'
  require 'html/pipeline'
rescue LoadError
  unless defined? Gem
    require 'rubygems'
    retry
  else
    abort $!.message
  end
ensure
  $-w = old_level
end

mdown_pipeline = HTML::Pipeline.new [
  HTML::Pipeline::MarkdownFilter,
  HTML::Pipeline::SanitizationFilter,
  HTML::Pipeline::ImageMaxWidthFilter,
  HTML::Pipeline::AutolinkFilter,
  HTML::Pipeline::TableOfContentsFilter,
  HTML::Pipeline::SyntaxHighlightFilter,
], :gfm => false, :detect_syntax => false

GitHub::Markup.markup('github/markdown', /md|mkdn?|mdown|markdown/) do |content|
  result = mdown_pipeline.call content
  result[:output]
end

puts GitHub::Markup.render(file)
