#!/usr/bin/env bash
set -e

command="$1"
if [ -z "$command" ]; then
  echo "usage: coral completions <command> [<args...>]" >&2
  exit 1
fi

command_path="$(command -v "coral-$command")"
if grep -we --complete "$command_path" >/dev/null; then
  shift
  exec "$command_path" --complete "$@"
fi
