#!/usr/bin/env bash
set -e
[ -n "$CORAL_DEBUG" ] && set -x

# yanked from rbenv
resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}
abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${CORAL_ROOT}" ]; then
  CORAL_ROOT="${HOME}/.coral"
else
  CORAL_ROOT="${CORAL_ROOT%/}"
fi
export CORAL_ROOT

libexec_path="$(abs_dirname "$0")"
export PATH="${libexec_path}:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec coral-help
  ;;
* )
  command_path="$(command -v "coral-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "${0}: no such command \`$command'" >&2
    exit 1
  fi

  shift 1

  if [ $# -eq 1 ] && [ "$1" = '-h' -o "$1" = '--help' ]; then
    exec coral-help "$command"
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
