#!/usr/bin/env bash
# Usage: coral list [<pattern>]
# Summary: List local repositories in Coral
# Help: Lists names of repositories in $CORAL_ROOT, optionally filtered to ones
# starting with <pattern>.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

if [ "$1" = '--complete' ]; then
  complete=1
  shift
fi

prefix="$1"

shopt -s failglob
set -o pipefail

{ for repo_dir in "$CORAL_ROOT/repos/${prefix}"*; do
  [[ ! -L ${repo_dir}/.git/config ]] || continue
  name=${repo_dir##*/}
  if [ -n "$complete" ]; then
    echo ${name%@*}
  else
    versions="$(coral-list-checkouts "$name")"
    echo ${name%@*} "(${versions//$'\n'/, })"
  fi
done
} | sort --ignore-case
