#!/usr/bin/env bash
# Usage: coral gem-browse <gem-name>
# Summary: Open gem's home page in the browser

set -e
[ -n "$CORAL_DEBUG" ] && set -x

homepage="$(coral-gem-spec-read homepage "$1")"

exec git web--browse $homepage
