#!/usr/bin/env bash
# Usage: coral gem-clone <gem-name> [<clone-args...>]
# Summary: Clone a GitHub project for a gem
# Help: Attempts to clone gem's source code from GitHub.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

url="$(coral-gem-project-url "$1" git)"
shift 1

exec git clone $url "$@"
