#!/usr/bin/env bash
# Usage: coral gem-standalone <gem-name> [<gem-version>]
# Summary: Install a Ruby gem as a standalone utility
# Help: Installs a Ruby gem into $prefix ("/usr/local" by default) using
# Bundler to make its runtime self-contained, and putting its executables into
# "$prefix/bin".  Running the installed executables doesn't require RubyGems or
# Bundler anymore.
#
# This is useful for gems that are command-line tools, but the overhead of
# RubyGems and activating its dependencies slows it down too much.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

gem_name="${1?}"
prefix="${prefix:-/usr/local}"

gemspec="$(coral-gem-spec-read loaded_from "$@")"
gem_dir="$(coral-gem-dir "$@")"

ruby_bin="$(ruby -r rbconfig -e '
  rb = RbConfig::CONFIG
  puts File.join(rb["bindir"], rb["ruby_install_name"])
')"

mkdir -p "${prefix}/lib/${gem_name}"
cd "${prefix}/lib/${gem_name}"

cp -R "$gem_dir"/lib/ .
cp "$gemspec" .

echo "source :rubygems; gemspec" > Gemfile

bundle install --path vendor --without development:test --standalone

for binfile in "${gem_dir}/bin/"*; do
  if head -1 "$binfile" | grep ruby >/dev/null; then
    destfile="${prefix}/bin/$(basename "$binfile")"

    { echo "#!${ruby_bin} -r $(pwd)/vendor/bundler/setup"
      echo "\$LOAD_PATH[0] = '$(pwd)'"
      cat "$binfile"
    } > "$destfile"

    chmod +x "$destfile"
  fi
done
