#!/usr/bin/env bash

set -e
[ -n "$CORAL_DEBUG" ] && set -x

html=$(coral-github-markup "$1")

echo "<style type='text/css'>"
cat "$(dirname "$0")/../resource/readme.css"
echo "</style>"
echo ""

echo "$html"
