#!/bin/sh
# Usage: coral find-readme <dir>
# Summary: Find README files in directory
# Help: Finds files named "README*" in the given directory.
#
# Does not recurse into nested directories.

find "$@" -maxdepth 1 -iname 'readme*' | sort
