#!/usr/bin/env ruby
## Extract information from gemspecs in the current bundle.
#
# Arguments:
#   - method name to read from gem spec;
#     supports special value "lib_dirs"

require 'rubygems'
require 'bundler'

$\ = "\n"
$, = "\t"
with_name = ARGV.delete '--with-name'
with_version = ARGV.delete '--with-version'
method = ARGV[0]

begin
  specs = Bundler.load.specs
rescue
  abort $!.message
else
  case method
  when 'lib_dirs'
    dirs = Dir.glob(specs.map {|spec| spec.lib_dirs_glob })
    print dirs.join($\)
  else
    errors = []
    specs.each { |spec|
      begin
        value = spec.send(method)
      rescue
        $stderr.puts $!.message
        exit 2
      else
        unless value.nil? or value.respond_to?(:empty?) && value.empty?
          values = []
          values << spec.name    if with_name
          values << spec.version if with_version

          if value.respond_to? :join
            value.each {|v| print(* values + [v.to_s]) }
          else
            values << value.to_s
            print(*values)
          end
        end
      end
    }
  end
end
