#!/usr/bin/env bash
# Usage: coral binstub [-f | --force] <repo>[@<version>]
# Summary: Install binstubs for a repo to $CORAL_ROOT/bin
# Help: Installs binstubs for the specified repo to $CORAL_ROOT/bin, which
# should be already present in your $PATH. This enables accessing executables
# from locally cloned projects.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

if [ "$1" = '--complete' ]; then
  shift
  exec coral-path --complete "$@"
fi

if [[ $1 = "--force" || $1 = "-f" ]]; then
  force=1
  shift 1
fi

repo="$(coral-path "$1")"
repo_rel="..${repo#$CORAL_ROOT}"

cd "$repo"

for binfile in bin/*; do
  bindest="${CORAL_ROOT}/${binfile}"

  if [[ -n $force || ! -e $bindest ]]; then
    if head -1 "$binfile" | grep ruby >/dev/null; then
      { echo "#!/bin/sh"
        echo "dir=\"\$(cd \"\$(dirname \"\$0\")/${repo_rel}\" && pwd)\""
        echo "RUBYLIB=\"\${dir}/lib:\$RUBYLIB\" \"\${dir}/${binfile}\" \"\$@\""
      } > "$bindest"
      chmod +x "$bindest"
      echo "installed $bindest"
    else
      ln -shfv "${repo_rel}/${binfile}" "$bindest"
    fi
  else
    echo "$bindest already exists" >&2
    exit 1
  fi
done
