#!/usr/bin/env bash
set -e
[ -n "$CORAL_DEBUG" ] && set -x

TMPDIR=${TMPDIR:-/tmp}

if [[ $1 = --clear-cache ]]; then
  rm -rf "${TMPDIR%/}/coral"
  exit
fi

url="${1?}"
shift 1

cache="${TMPDIR%/}/coral/${url#*://}"
expires="60 * 60 * 24"

if [[ $(date +%s) -lt "$(stat -qf %m "$cache") + $expires" ]]; then
  cat "$cache"
else
  mkdir -p "$(dirname "$cache")"
  curl -fsSLG "$url" "$@" | tee "$cache"
fi
