#!/usr/bin/env bash
# Usage: coral gem-dir <gem-name> [<gem-version>]
# Summary: Print the root directory of a gem
# Help: Outputs the filesystem path for a gem's root directory.
#
# If there is a Gemfile and there is no version constraint, the gem is searched
# for in the current bundle first.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

if [ $# -lt 2 ] && [ -n "$BUNDLE_GEMFILE" -o -f Gemfile ]; then
  dir="$(bundle show "$1" --no-color 2>/dev/null || true)"
fi

if [ -d "$dir" ]; then
  echo "$dir"
else
  coral-gem-spec-read full_gem_path "$@"
fi
