#!/usr/bin/env ruby -n
## Extracts github project "owner/repo_name" pair from URLs in input.

BEGIN {
  name  = /\w[\w.-]*/
  owner = /[a-zA-Z0-9-]+/
  url1  = %r{ :// (?:wiki\.)? github\.com / (#{owner}) / (#{name})  }x
  url2  = %r{ :// (#{owner}) \. github\.com / (#{name}) }x
}

puts "#$1/#{$2.sub(/\.git$/, '')}" if $_ =~ url1 or $_ =~ url2
