#!/usr/bin/env bash
# Usage: coral gem-browse-project <gem-name> [<subpage>]
# Summary: Open GitHub project page for a gem
# Help: Opens the gem's GitHub project page in the web browser.
#
# The <subpage> can be, for example:
# - issues
# - pulls
# - wiki
# - commits
#
# Uses the `git web--browse` command.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

url="$(coral-gem-project-url "$1")"

# add subpage
[ -n "$2" ] && url=${url%/}/${2#/}

exec git web--browse $url
