#!/usr/bin/env bash
# Usage: coral list [<pattern>]
# Summary: List local repositories in Coral
# Help: Lists names of repositories in $CORAL_ROOT, optionally filtered to ones
# starting with <pattern>.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

prefix="$1"

shopt -s failglob
set -o pipefail

{ for repo_dir in "$CORAL_ROOT/repos/${prefix}"*; do
  if [[ ! -L ${repo_dir}/.git/config ]]; then
    name=$(basename "$repo_dir")
    versions="$(coral-list-checkouts "$name")"
    echo ${name%@*} "(${versions//$'\n'/, })"
  fi
done
} | sort --ignore-case
