#!/usr/bin/env bash
set -e
[ -n "$CORAL_DEBUG" ] && set -x

prefix="$1"

{ for repo_dir in "$CORAL_ROOT/repos/${prefix}"*; do
  if [[ ! -L ${repo_dir}/.git/config ]]; then
    name=$(basename "$repo_dir")
    versions="$(coral-list-checkouts "$name")"
    echo ${name%@*} "(${versions//$'\n'/, })"
  fi
done
} | sort --ignore-case
