#!/usr/bin/env bash
# Usage: coral bundle-ack <search-term> [<options...>]
# Summary: Search inside the current bundle
# Help: Searches through source code of each gem in the bundle. Search is
# powered by ack and all arguments are forwarded to it. By default,
# <search-term> is interpreted as a Perl-compatible regex.
#
# See `ack --help`

set -e
[ -n "$CORAL_DEBUG" ] && set -x

dirs="$(coral-bundle-spec-read lib_dirs)"

exec ack --ruby "$@" $dirs
