#!/usr/bin/env bash
# Usage: coral gem-open <gem-name> [<gem-version>]
# Summary: Open gem's source code in the text editor
# Help: Opens a gem's source code in the text editor. If there is a Gemfile and
# there is no version constraint, first tries to locate the gem as part of the
# bundle.
#
# If there is a README file as part of the gem, it will be opened initially.
#
# The editor program is read from $GEM_EDITOR, then $VISUAL, then $EDITOR.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

dir="$(coral-gem-dir "$@")"
readme="$(coral-find-readme "$dir" | head -1)"

EDITOR="${VISUAL:-$EDITOR}"
EDITOR="${GEM_EDITOR:-$EDITOR}"
export EDITOR

if [[ -z $readme ]]; then
  exec coral-open-dir "$dir"
else
  exec coral-open-dir "$dir" "$readme"
fi
