#!/usr/bin/env bash
# Usage: coral commands [-v]
# Summary: List available commands
# Help: Lists coral commands available on the system.
# This searches the whole PATH for executables starting with "coral-".
#
# It outputs only the command names. To get full paths, use `-v`.

set -e
[ -n "$CORAL_DEBUG" ] && set -x

unset verbose
unset sh

case "$1" in
"-v" )
  verbose=1
  shift
  ;;
"--sh" )
  sh=1
  shift
  ;;
esac

shopt -s nullglob

{ for path in ${PATH//:/$'\n'}; do
    for command in "${path}/coral-"*; do
      if [ -x "$command" ]; then
        [ -z $verbose ] && command=${command##*coral-}
        if [ -z "$sh" -o ${command:0:3} = "sh-" ]; then
          echo ${command#sh-}
        fi
      fi
    done
  done
} | sort | uniq
