#!/usr/bin/env bash
set -e
[ -n "$CORAL_DEBUG" ] && set -x

# yanked from rbenv
resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}
abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${CORAL_ROOT}" ]; then
  CORAL_ROOT="${HOME}/.coral"
else
  CORAL_ROOT="${CORAL_ROOT%/}"
fi
export CORAL_ROOT

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "coral 0.1\n$(coral-help)" >&2
  ;;
* )
  command_path="$(command -v "coral-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "${0}: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
