#!/usr/bin/env bash
# Usage: coral open-dir <dir> [<editor-args...>]
# Summary: Open a project in a directory in the text editor
# Help: Opens a project in the specified directory in $EDITOR.
#
# If the editor is Vim, these special features are supported:
# - automatically cd into the directory inside Vim
# - passing of additional files to open buffers for, such as "README"
# - passing of extra arguments, such as `-t <tag>`

set -e
[ -n "$CORAL_DEBUG" ] && set -x

dir="$1"
[[ $# -gt 1 ]] && shift

EDITOR="${EDITOR:-vi}"

case ${EDITOR%% *} in
vim | mvim | gvim )
  exec $EDITOR --cmd "cd ${dir// /\\ }" --cmd 'set tags^=.git/tags' "$@"
  ;;
* )
  exec $EDITOR "$dir"
  ;;
esac
