#!/usr/bin/env bash
set -e
[ -n "$CORAL_DEBUG" ] && set -x

gem_name="${1?}"
[[ -n $prefix ]] || prefix=/usr/local

gemspec="$(coral-gem-spec-read loaded_from "$@")"
gem_dir="$(coral-gem-dir "$@")"

ruby_bin="$(ruby -r rbconfig -e '
  rb = RbConfig::CONFIG
  puts File.join(rb["bindir"], rb["ruby_install_name"])
')"

mkdir -p "${prefix}/lib/${gem_name}"
cd "${prefix}/lib/${gem_name}"

cp -R "$gem_dir"/lib/ .
cp "$gemspec" .

echo "source :rubygems; gemspec" > Gemfile

bundle install --path vendor --without development --standalone

for binfile in "${gem_dir}/bin/"*; do
  if head -1 "$binfile" | grep ruby >/dev/null; then
    destfile="${prefix}/bin/$(basename "$binfile")"

    { echo "#!${ruby_bin} -r $(pwd)/vendor/bundler/setup"
      echo "\$LOAD_PATH[0] = '$(pwd)'"
      cat "$binfile"
    } > "$destfile"

    chmod +x "$destfile"
  fi
done
